### ISSUE TITLE
logging in w/ github overrides a user's username and displayname

### ISSUE THREAD

**Issue by lastlink** [kanboard/plugin-github-auth#1]
I don't know if this is the intended result, but after logging in w/ github to an account that has been linked with it I've noticed that my username & display name always change to that of my github account. I can understand if someone created an account from github to do this, but after an account already exists the desired result is not to copy a user's information from github's oauth every time.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
